name: app_event
description: App event handle event without using stream
version: 1.0.0
repository: https://github.com/mj-codedev/app_event

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
